name: Verify PR & comment

on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Retrieve version from VERSION
        run: |
          RELVER=$(cat VERSION | tr -d '[:space:]')
          echo "RELVER=$RELVER" >> $GITHUB_ENV
          
      - name: Create version.js
        run: |
          echo "module.exports = { tag: '${{ env.RELVER }}' }" > version.js
          
      - name: Install md-to-pdf
        run: npm install -g md-to-pdf
          
      - name: Create PDF of readme
        run: cat README.md | md-to-pdf --config-file doc-config.js > readme.pdf
      
      - name: Append version to assets
        run: |
          cp readme.pdf readme-${{ env.RELVER }}.pdf
          cp "app/Reload Analyzer.qvf" "app/Reload Analyzer ${{ env.RELVER }}.qvf"
      
      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ./readme-${{ env.RELVER }}.pdf
          message: |
            To do:
            
            - [ ] Is this release [${{ env.RELVER }}]? (if no, or if this is blank, update VERSION (e.g. 'v1.0.0'))
            - [ ] Has the attached PDF generated correctly?
            
            If you wish to merge:

            - Merge this PR into main
            - Go to releases, an action will generate a draft release with docs + attached QVF
            - Make any updates, then submit the release

            Common issues:
            
            - Version number missing or incorrect (./VERSION file needs updating)
            - PDF doesn't generate (./VERSION file has invalid characters)
            - After merging, draft release doesn't update - this is usually because
              the action failed due to an old draft release. Delete the draft release,
              and re-run the action
